import pygame

WIDTH = 500
HEIGHT = 500
GOTOMAINMENU = pygame.USEREVENT + 1
CREATENEWLEVEL = GOTOMAINMENU + 1
CHOOSEPLAYERS = CREATENEWLEVEL + 1
UPDATE_SPRITES = 30
STEP = 4
WALL = 0
EMPTY = 1
ENTER = 2
EXIT = 3
COIN = 4
BLACK = pygame.Color('black')